/* ============================================================
   REALTOR SITE TEMPLATE — Listings data layer
   Seed data ships with the site; the admin panel saves edits
   to localStorage, which overrides the seed for this browser.
   ============================================================ */

const HR_STORE_KEY = "hr_listings_v1";

/* Listings seed is generated by build.py from site.config.json.
   The admin panel persists edits to localStorage. */
const HR_SEED_LISTINGS = [
  {
    "id": "recent-1",
    "status": "sold",
    "address": "524 Washington Blvd",
    "city": "Kansas City",
    "state": "KS",
    "zip": "66101",
    "price": null,
    "beds": 4,
    "baths": 2,
    "sqft": 1721,
    "image": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    "description": "Public profile shows this as a recent seller-side closing. Demo image is placeholder.",
    "featured": true
  },
  {
    "id": "recent-2",
    "status": "sold",
    "address": "8728 Grandview St",
    "city": "Overland Park",
    "state": "KS",
    "zip": "66212",
    "price": null,
    "beds": 4,
    "baths": 1,
    "sqft": 1626,
    "image": "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1200&q=80",
    "description": "Public profile shows this as a recent buyer-side closing. Demo image is placeholder.",
    "featured": true
  },
  {
    "id": "active-1",
    "status": "for-sale",
    "address": "2727 Vine St",
    "city": "Kansas City",
    "state": "MO",
    "zip": "64109",
    "price": 220000,
    "beds": 6,
    "baths": 2,
    "sqft": 2024,
    "image": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    "description": "Public Zillow profile shows this as an active listing under At Home Kansas. Demo image is placeholder.",
    "featured": false
  }
];

const HRData = {
  getAll() {
    try {
      const raw = localStorage.getItem(HR_STORE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch (e) { /* corrupted store — fall back to seed */ }
    return structuredClone(HR_SEED_LISTINGS);
  },

  saveAll(listings) {
    localStorage.setItem(HR_STORE_KEY, JSON.stringify(listings));
  },

  reset() {
    localStorage.removeItem(HR_STORE_KEY);
  },

  hasCustomData() {
    return localStorage.getItem(HR_STORE_KEY) !== null;
  },

  statusLabel(status) {
    return { "for-sale": "For Sale", "pending": "Pending", "sold": "Sold" }[status] || status;
  },

  formatPrice(listing) {
    if (listing.status === "sold") {
      return listing.price ? "Sold · " + HRData.money(listing.price) : "Sold";
    }
    return listing.price ? HRData.money(listing.price) : "Price on request";
  },

  money(n) {
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency: "USD", maximumFractionDigits: 0
    }).format(n);
  }
};
