/* ============================================================
   REALTOR SITE TEMPLATE — Listings data layer
   Seed data ships with the site; the admin panel saves edits
   to localStorage, which overrides the seed for this browser.
   ============================================================ */

const HR_STORE_KEY = "hr_listings_v1";

/* Listings seed is generated by build.py from site.config.json.
   The admin panel persists edits to localStorage. */
const HR_SEED_LISTINGS = [
  {
    "id": "sample-1",
    "status": "for-sale",
    "address": "5812 State Line Rd [SAMPLE]",
    "city": "Mission Hills",
    "state": "KS",
    "zip": "66208",
    "price": 2250000,
    "beds": 6,
    "baths": 6,
    "sqft": 7800,
    "image": "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Iconic Mission Hills estate on a corner lot \u2014 six ensuite bedrooms, chef's kitchen, pool, and a carriage house guest suite.",
    "featured": true
  },
  {
    "id": "sample-2",
    "status": "for-sale",
    "address": "18 Lakeview Ct [SAMPLE]",
    "city": "Lake Lotawana",
    "state": "MO",
    "zip": "64086",
    "price": 875000,
    "beds": 4,
    "baths": 4,
    "sqft": 3400,
    "image": "https://images.unsplash.com/photo-1602941525421-8f8b81d3edbb?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Breathtaking lake-front home on a private cove at Lake Lotawana \u2014 deep-water dock, vaulted great room, wraparound deck.",
    "featured": true
  },
  {
    "id": "sample-3",
    "status": "sold",
    "address": "10216 Roe Ave [SAMPLE]",
    "city": "Leawood",
    "state": "KS",
    "zip": "66206",
    "price": null,
    "beds": 5,
    "baths": 5,
    "sqft": 5100,
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Stunning Leawood new-build \u2014 soaring ceilings, quartz waterfall island, main-floor primary, and a resort-style walk-out lower level.",
    "featured": false
  }
];

const HRData = {
  getAll() {
    try {
      const raw = localStorage.getItem(HR_STORE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch (e) { /* corrupted store — fall back to seed */ }
    return structuredClone(HR_SEED_LISTINGS);
  },

  saveAll(listings) {
    localStorage.setItem(HR_STORE_KEY, JSON.stringify(listings));
  },

  reset() {
    localStorage.removeItem(HR_STORE_KEY);
  },

  hasCustomData() {
    return localStorage.getItem(HR_STORE_KEY) !== null;
  },

  statusLabel(status) {
    return { "for-sale": "For Sale", "pending": "Pending", "sold": "Sold" }[status] || status;
  },

  formatPrice(listing) {
    if (listing.status === "sold") {
      return listing.price ? "Sold · " + HRData.money(listing.price) : "Sold";
    }
    return listing.price ? HRData.money(listing.price) : "Price on request";
  },

  money(n) {
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency: "USD", maximumFractionDigits: 0
    }).format(n);
  }
};
