/* ============================================================
   REALTOR SITE TEMPLATE — Listings data layer
   Seed data ships with the site; the admin panel saves edits
   to localStorage, which overrides the seed for this browser.
   ============================================================ */

const HR_STORE_KEY = "hr_listings_v1";

/* Listings seed is generated by build.py from site.config.json.
   The admin panel persists edits to localStorage. */
const HR_SEED_LISTINGS = [
  {
    "id": "tool-1",
    "status": "for-sale",
    "address": "Home Value Review",
    "city": "Johnson County",
    "state": "KS",
    "zip": "66210",
    "price": null,
    "beds": 0,
    "baths": 0,
    "sqft": 0,
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    "description": "Demo card: a cleaner path to request a pricing conversation before listing.",
    "featured": true
  },
  {
    "id": "tool-2",
    "status": "pending",
    "address": "Buyer Readiness Plan",
    "city": "Kansas City",
    "state": "KS",
    "zip": "66101",
    "price": null,
    "beds": 0,
    "baths": 0,
    "sqft": 0,
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80",
    "description": "Demo card: prequalification, budget, neighborhood fit, and offer strategy in one guided flow.",
    "featured": true
  },
  {
    "id": "tool-3",
    "status": "sold",
    "address": "Investor Worksheet",
    "city": "Lenexa",
    "state": "KS",
    "zip": "66215",
    "price": null,
    "beds": 0,
    "baths": 0,
    "sqft": 0,
    "image": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    "description": "Demo card: cash-flow, tax-proration, and rental analysis tools packaged for investors.",
    "featured": false
  }
];

const HRData = {
  getAll() {
    try {
      const raw = localStorage.getItem(HR_STORE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch (e) { /* corrupted store — fall back to seed */ }
    return structuredClone(HR_SEED_LISTINGS);
  },

  saveAll(listings) {
    localStorage.setItem(HR_STORE_KEY, JSON.stringify(listings));
  },

  reset() {
    localStorage.removeItem(HR_STORE_KEY);
  },

  hasCustomData() {
    return localStorage.getItem(HR_STORE_KEY) !== null;
  },

  statusLabel(status) {
    return { "for-sale": "For Sale", "pending": "Pending", "sold": "Sold" }[status] || status;
  },

  formatPrice(listing) {
    if (listing.status === "sold") {
      return listing.price ? "Sold · " + HRData.money(listing.price) : "Sold";
    }
    return listing.price ? HRData.money(listing.price) : "Price on request";
  },

  money(n) {
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency: "USD", maximumFractionDigits: 0
    }).format(n);
  }
};
