/* ============================================================
   REALTOR SITE TEMPLATE — Listings data layer
   Seed data ships with the site; the admin panel saves edits
   to localStorage, which overrides the seed for this browser.
   ============================================================ */

const HR_STORE_KEY = "hr_listings_v1";

/* Listings seed is generated by build.py from site.config.json.
   The admin panel persists edits to localStorage. */
const HR_SEED_LISTINGS = [
  {
    "id": "sample-1",
    "status": "for-sale",
    "address": "4820 W 113th St [SAMPLE]",
    "city": "Leawood",
    "state": "KS",
    "zip": "66211",
    "price": 698000,
    "beds": 5,
    "baths": 4,
    "sqft": 3780,
    "image": "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Sprawling Leawood two-story with main-floor primary, open-concept kitchen, and finished walk-out basement with home theater.",
    "featured": true
  },
  {
    "id": "sample-2",
    "status": "pending",
    "address": "14012 W 88th Terrace [SAMPLE]",
    "city": "Lenexa",
    "state": "KS",
    "zip": "66215",
    "price": 459000,
    "beds": 4,
    "baths": 3,
    "sqft": 2640,
    "image": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Like-new Lenexa four-bedroom with updated kitchen, three-car garage, and a beautifully landscaped fenced yard.",
    "featured": true
  },
  {
    "id": "sample-3",
    "status": "sold",
    "address": "5200 W 99th Pl [SAMPLE]",
    "city": "Overland Park",
    "state": "KS",
    "zip": "66207",
    "price": null,
    "beds": 3,
    "baths": 2,
    "sqft": 1820,
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Updated Overland Park ranch in a sought-after neighborhood near top-rated schools, sold above asking in four days.",
    "featured": false
  }
];

const HRData = {
  getAll() {
    try {
      const raw = localStorage.getItem(HR_STORE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch (e) { /* corrupted store — fall back to seed */ }
    return structuredClone(HR_SEED_LISTINGS);
  },

  saveAll(listings) {
    localStorage.setItem(HR_STORE_KEY, JSON.stringify(listings));
  },

  reset() {
    localStorage.removeItem(HR_STORE_KEY);
  },

  hasCustomData() {
    return localStorage.getItem(HR_STORE_KEY) !== null;
  },

  statusLabel(status) {
    return { "for-sale": "For Sale", "pending": "Pending", "sold": "Sold" }[status] || status;
  },

  formatPrice(listing) {
    if (listing.status === "sold") {
      return listing.price ? "Sold · " + HRData.money(listing.price) : "Sold";
    }
    return listing.price ? HRData.money(listing.price) : "Price on request";
  },

  money(n) {
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency: "USD", maximumFractionDigits: 0
    }).format(n);
  }
};
