/* ============================================================
   REALTOR SITE TEMPLATE — Listings data layer
   Seed data ships with the site; the admin panel saves edits
   to localStorage, which overrides the seed for this browser.
   ============================================================ */

const HR_STORE_KEY = "hr_listings_v1";

/* Listings seed is generated by build.py from site.config.json.
   The admin panel persists edits to localStorage. */
const HR_SEED_LISTINGS = [
  {
    "id": "sample-1",
    "status": "for-sale",
    "address": "4217 NE Antioch Rd [SAMPLE]",
    "city": "Kansas City",
    "state": "MO",
    "zip": "64117",
    "price": 284000,
    "beds": 3,
    "baths": 2,
    "sqft": 1480,
    "image": "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Updated Northland ranch with open living area, new kitchen, and fenced yard \u2014 strong rental upside or perfect first home.",
    "featured": true
  },
  {
    "id": "sample-2",
    "status": "for-sale",
    "address": "608 SW Market St [SAMPLE]",
    "city": "Lee's Summit",
    "state": "MO",
    "zip": "64063",
    "price": 369000,
    "beds": 4,
    "baths": 3,
    "sqft": 2210,
    "image": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Four-bedroom two-story near downtown Lee's Summit with updated baths, large deck, and great school district.",
    "featured": true
  },
  {
    "id": "sample-3",
    "status": "sold",
    "address": "1422 S Hardy Ave [SAMPLE]",
    "city": "Independence",
    "state": "MO",
    "zip": "64052",
    "price": null,
    "beds": 3,
    "baths": 1,
    "sqft": 1120,
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Investor-ready Independence bungalow \u2014 solid bones, tenant already in place, strong cash flow from day one.",
    "featured": false
  }
];

const HRData = {
  getAll() {
    try {
      const raw = localStorage.getItem(HR_STORE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch (e) { /* corrupted store — fall back to seed */ }
    return structuredClone(HR_SEED_LISTINGS);
  },

  saveAll(listings) {
    localStorage.setItem(HR_STORE_KEY, JSON.stringify(listings));
  },

  reset() {
    localStorage.removeItem(HR_STORE_KEY);
  },

  hasCustomData() {
    return localStorage.getItem(HR_STORE_KEY) !== null;
  },

  statusLabel(status) {
    return { "for-sale": "For Sale", "pending": "Pending", "sold": "Sold" }[status] || status;
  },

  formatPrice(listing) {
    if (listing.status === "sold") {
      return listing.price ? "Sold · " + HRData.money(listing.price) : "Sold";
    }
    return listing.price ? HRData.money(listing.price) : "Price on request";
  },

  money(n) {
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency: "USD", maximumFractionDigits: 0
    }).format(n);
  }
};
