/* ============================================================
   REALTOR SITE TEMPLATE — Listings data layer
   Seed data ships with the site; the admin panel saves edits
   to localStorage, which overrides the seed for this browser.
   ============================================================ */

const HR_STORE_KEY = "hr_listings_v1";

/* Listings seed is generated by build.py from site.config.json.
   The admin panel persists edits to localStorage. */
const HR_SEED_LISTINGS = [
  {
    "id": "sample-1",
    "status": "for-sale",
    "address": "4200 Main Street [SAMPLE]",
    "city": "Kansas City",
    "state": "MO",
    "zip": "64111",
    "price": 2850000,
    "beds": 0,
    "baths": 0,
    "sqft": 8400,
    "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Class B office building near Country Club Plaza. Multi-tenant configuration, recently renovated common areas.",
    "featured": true
  },
  {
    "id": "sample-2",
    "status": "for-sale",
    "address": "7100 College Blvd [SAMPLE]",
    "city": "Overland Park",
    "state": "KS",
    "zip": "66210",
    "price": 1650000,
    "beds": 0,
    "baths": 0,
    "sqft": 5200,
    "image": "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Retail strip center on College Blvd, high-traffic corridor, strong anchor tenant in place.",
    "featured": true
  },
  {
    "id": "sample-3",
    "status": "pending",
    "address": "1 Lightwell Dr [SAMPLE]",
    "city": "Kansas City",
    "state": "MO",
    "zip": "64108",
    "price": null,
    "beds": 0,
    "baths": 0,
    "sqft": 3100,
    "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80",
    "description": "[SAMPLE \u2014 CONCEPT DEMO] Creative office suite in the Crossroads district. Open floor plan with exposed brick, ideal for tech or creative tenants.",
    "featured": false
  }
];

const HRData = {
  getAll() {
    try {
      const raw = localStorage.getItem(HR_STORE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch (e) { /* corrupted store — fall back to seed */ }
    return structuredClone(HR_SEED_LISTINGS);
  },

  saveAll(listings) {
    localStorage.setItem(HR_STORE_KEY, JSON.stringify(listings));
  },

  reset() {
    localStorage.removeItem(HR_STORE_KEY);
  },

  hasCustomData() {
    return localStorage.getItem(HR_STORE_KEY) !== null;
  },

  statusLabel(status) {
    return { "for-sale": "For Sale", "pending": "Pending", "sold": "Sold" }[status] || status;
  },

  formatPrice(listing) {
    if (listing.status === "sold") {
      return listing.price ? "Sold · " + HRData.money(listing.price) : "Sold";
    }
    return listing.price ? HRData.money(listing.price) : "Price on request";
  },

  money(n) {
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency: "USD", maximumFractionDigits: 0
    }).format(n);
  }
};
